apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l7-visibility"
spec:
  endpointSelector:
    matchLabels:
      app: argocd-server
  ingress:
  - toPorts:
    - ports:
      - port: "8080"
        protocol: TCP