apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l7-visibility"
spec:
  endpointSelector:
    matchLabels:
      namespace: argocd
  ingress:
  - toPorts:
    - ports:
      - protocol: "ANY"