apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l7-visibility"
spec:
  endpointSelector:
    matchLabels:
      "k8s:io.kubernetes.pod.namespace": argocd
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": argocd
      toPorts:
        - ports:
            - port: "8080"
              protocol: ANY
            - port: "80"
              protocol: ANY
            - port: "443"
              protocol: ANY
  ingress:
  - toPorts:
    - ports:
      - port: "8080"
        protocol: ANY
      - port: "80"
        protocol: ANY
      - port: "443"
        protocol: ANY